import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalLayout from "@/components/GlobalLayout";
import StoreProvider from "@/redux/StoreProvider";
import { NotificationProvider } from "@/components/notification/NotificationContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NotificationProvider>
          <StoreProvider>
            <GlobalLayout>
              <main className="flex-1 w-full  max-w-7xl mx-auto px-4 md:px-6 pt-8 md:pt-12 pb-16 mb-8 mt-8">
                {children}
              </main>
            </GlobalLayout>
          </StoreProvider>
        </NotificationProvider>

      </body>
    </html>
  );
}
